version: '3.3'
networks:
  network:
    driver: bridge

services:
  localstack:
     image: localstack/localstack:1.0.4
     networks:
      - network
     environment: 
      - SERVICES=s3:4566
      - HOSTNAME=localstack 
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=us-east-1

  aws-cli:
    image: amazon/aws-cli
    restart: on-failure
    networks:
      - network
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket bucket --region us-east-1
      "
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: gitOrch-backend
    networks:
      - network
    ports:
      - "8080:8080" 
    env_file:
      - env.list
    depends_on:
      - redis
      - postgres 
    restart: unless-stopped 
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: gitOrch-frontend
    networks:
      - network
    env_file: 
      - env.list
    ports:
      - "3000:3000" 
    restart: unless-stopped


  postgres:
    image: postgres:latest
    networks:
      - network
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: sudo
      POSTGRES_PASSWORD: sudo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    networks:
       - network
    ports:
      - "6379:6379"
