version: '3.3'
networks:
  network:
    driver: bridge
services:

  postgres:
    image: postgres:latest
    networks:
      - network
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: sudo
      POSTGRES_PASSWORD: sudo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    networks:
       - network
    ports:
      - "6379:6379"
