version: '3.3'
services:
  api:
    build:
      context: ./
      dockerfile: local.Dockerfile 
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app 
    command: sh run.sh
    env_file:
      - .env 
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: activity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: