

blank_issues_enabled: false
contact_links:
  - name: Ask Question
    url: https://github.com/mdgspace/activity-leaderboard-backend/discussions
    about: Please go to GitHub Disccusions to ask questions
