name: CI Workflow
on: 
 pull_request:
    branches: [ masterm main ]
    paths:
        - 'src/**'
 push:
    branches: [master, main]
    paths:
        - 'src/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 17
            - name: Build and test
              run: mvn clean install